
[build]
publish = "C:\\Users\\Asus\\OneDrive\\Escritorio\\Personal\\1Gb of mem\\Mem2U\\react\\react\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\Asus\\OneDrive\\Escritorio\\Personal\\1Gb of mem\\Mem2U\\react"
command = "npm --workspace react-app run build"
functions = "functions"


[[redirects]]
  from = "/api/*"
  to = "/netlify/functions/:splat"
  status = 200