functionsDirectory = "C:\\Users\\Asus\\OneDrive\\Escritorio\\Personal\\1Gb of mem\\Mem2U\\react\\functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Asus\\OneDrive\\Escritorio\\Personal\\1Gb of mem\\Mem2U\\react\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\Asus\\OneDrive\\Escritorio\\Personal\\1Gb of mem\\Mem2U\\react"
command = "npm run build"
functions = "C:\\Users\\Asus\\OneDrive\\Escritorio\\Personal\\1Gb of mem\\Mem2U\\react\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200